version: "3"
services:
  db:
    image: arm64v8/postgres:latest
    ports:
      - "127.0.0.1:32768:5432"
    environment:
      POSTGRES_DB: "santa"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: always