version: "3"
services:
  db:
    image: postgres:latest
    ports:
      - "127.0.0.1:32768:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./sql/v7.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: always